### ISSUE TITLE
new Notification() is on the path to deprecation

### ISSUE THREAD

**Issue by juangabrielr4** [mdn/to-do-notifications#4]
i can't get this working on android [here is why](https://bugs.chromium.org/p/chromium/issues/detail?id=481856)

**Comment by chrisdavidmills** [comment]
Thanks for the heads-up on this. I will investigate what we are doing about this in Gecko, and put this into our documentation schedule as appropriate. We have a bunch of Notification demos and docs, and it will make sense to fix them all in one go as a dedicated work item, rather than getting to them randomly as we go.
